# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\ncalculator\".\n\nAddRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\"\x1a\n\x08\x41\x64\x64Reply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x43\n\nCalculator\x12\x35\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x14.calculator.AddReply\"\x00\x42#\n\x10\x63om.example.grpcB\x0f\x43\x61lculatorProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.example.grpcB\017CalculatorProto'
  _globals['_ADDREQUEST']._serialized_start=25
  _globals['_ADDREQUEST']._serialized_end=71
  _globals['_ADDREPLY']._serialized_start=73
  _globals['_ADDREPLY']._serialized_end=99
  _globals['_CALCULATOR']._serialized_start=101
  _globals['_CALCULATOR']._serialized_end=168
# @@protoc_insertion_point(module_scope)
